apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - db-init-job.yaml
  - ingress.yaml

images:
  - name: vmware-inv-backend
    newTag: v1.0.0
  - name: vmware-inv-frontend
    newTag: v1.0.0
